name:                parcial-funcional
version:             0.1.0.0
github:              "pdep-lunes/parcial-funcional"
license:             BSD3
author:              "PdeP Lunes"
maintainer:          "pdep-lunes"
copyright:           "2020 pdep-lunes utn-frba"

extra-source-files:
- readme.md

description:         Please see the README on GitHub at <https://github.com/pdep-lunes/parcial-funcional#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - RebindableSyntax

library:
  source-dirs: src

tests:
  parcial-funcional-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parcial-funcional
    - hspec
